services:
  db:
    image: postgres:17
    container_name: centurion_riwi-postgres

    environment:
      POSTGRES_DB: bd_andrea_ahumada_centurion
      POSTGRES_USER: centurion
      POSTGRES_PASSWORD: 123456

    ports:
      - "5433:5432"

    volumes:
      - riwi-db-data:/var/lib/postgresql/data

volumes:
  riwi-db-data: